apiVersion: v1
kind: Service
metadata:
  name: {{ include "enthropic.fullname" . }}-{{ .Values.service.name }}
  labels:
    app: {{ include "enthropic.fullname" . }}
    service: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "enthropic.fullname" . }}
    service: {{ .Values.service.name }}
