apiVersion: v2
name: enthropic
description: Enthropic Trading Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - trading
  - fintech
  - microservices
maintainers:
  - name: Enthropic Team
    email: team@enthropic.io
